[package]
name = "cgroup-dev"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.66"
libbpf-rs = "0.19.1"
libc = "0.2.137"

[build-dependencies]
libbpf-cargo = "0.13.1"
